-- local data = 
-- {
--   colors = {"Red","Green","Blue","Purple","Orange","Yellow"},
--   ages = {23,56,65,23,54,12,42}
-- }

--skytable:random("ages", networkListener)
--skytable:slice("colors", 1, 4, networkListener)
--skytable:trim("colors", 1, 2, networkListener)
--skytable:remove("colors", 2, networkListener)
--skytable:insert("colors", 1, {"Pink","Brown"}, networkListener)
--skytable:unshift("colors", networkListener)
--skytable:shift("colors", "Purple", networkListener)
--skytable:pop("colors", networkListener)
--skytable:push("colors", "Purple", networkListener)
--skytable:indexOf("colors", "Blue", networkListener)
--skytable:arrlen("colors", networkListener)
--skytable:delete("score", networkListener)
--skytable:len("name", networkListener)
--skytable:keys(netListener)
--skytable:strappend("name", ", Frank", networkListener)
--skytable:strlen("name", networkListener)
--skytable:mult("score", 2, networkListener)
--skytable:dec("score", 2, networkListener)
--skytable:inc("score", 2, networkListener)
--skytable:set("score", 20, networkListener)
--skytable:set("profile.name", "Johnson", netListener)